package cn.lihongjie.jsxdocx;

import com.caoccao.javet.swc4j.Swc4j;
import com.caoccao.javet.swc4j.enums.Swc4jMediaType;
import com.caoccao.javet.swc4j.enums.Swc4jSourceMapOption;
import com.caoccao.javet.swc4j.options.Swc4jJsxRuntimeOption;
import com.caoccao.javet.swc4j.options.Swc4jTranspileOptions;
import com.caoccao.javet.swc4j.outputs.Swc4jTranspileOutput;

import java.net.URL;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Compiler {

    public String compile(String jsxCode) throws Exception {
        Swc4j swc4j = new Swc4j();

        URL specifier = new URL("file:///main.jsx");

        // Use Classic runtime with custom factories to avoid global React.
        // This prevents SWC from emitting ESM imports (which Rhino can't eval)
        // while still allowing concise JSX usage in tests.
        Swc4jJsxRuntimeOption jsxOption = Swc4jJsxRuntimeOption.Classic()
            .setFactory("React.createElement")
            .setFragmentFactory("React.Fragment");

        Swc4jTranspileOptions options = new Swc4jTranspileOptions()
                .setSpecifier(specifier)
                .setMediaType(Swc4jMediaType.Jsx)
                .setSourceMap(Swc4jSourceMapOption.None)
                .setJsx(jsxOption);

        Swc4jTranspileOutput output = swc4j.transpile(jsxCode, options);
        String compiled = output.getCode();
        
        // Post-process to convert arrow functions to regular functions for Rhino compatibility
        // Pattern: param => expression  OR  (params) => expression  OR  (params) => { body }
        compiled = convertArrowFunctions(compiled);
        
        return compiled;
    }
    
    /**
     * Convert ES6 arrow functions to ES5 function expressions for Rhino compatibility.
     * Handles simple cases commonly generated by SWC4J.
     * Note: This is a best-effort conversion and may not handle all edge cases.
     */
    private String convertArrowFunctions(String code) {
        // Pattern 1: Arrow functions with parenthesized expression bodies: (params) => (expr)
        // Convert to: function(params) { return (expr); }
        Pattern p1 = Pattern.compile("\\(([^)]*)\\)\\s*=>\\s*\\(([^)]+)\\)");
        Matcher m1 = p1.matcher(code);
        StringBuffer sb1 = new StringBuffer();
        while (m1.find()) {
            String params = m1.group(1);
            String expr = m1.group(2);
            // Use Matcher.quoteReplacement to handle special characters in replacement
            m1.appendReplacement(sb1, Matcher.quoteReplacement("function(" + params + ") { return (" + expr + "); }"));
        }
        m1.appendTail(sb1);
        code = sb1.toString();
        
        // Pattern 2: Block body: (params) => { body }
        // Convert to: function(params) { body }
        Pattern p2 = Pattern.compile("\\(([^)]*)\\)\\s*=>\\s*\\{");
        code = p2.matcher(code).replaceAll("function($1) {");
        
        // Pattern 3: Single param with block: x => { body }
        Pattern p3 = Pattern.compile("\\b([a-zA-Z_$][a-zA-Z0-9_$]*)\\s*=>\\s*\\{");
        code = p3.matcher(code).replaceAll("function($1) {");
        
        // Pattern 4: Parameters in parentheses with simple expression: (x, y) => expr
        // Convert to: function(x, y) { return expr; }
        // This must come after patterns that handle parenthesized expressions and blocks
        Pattern p4 = Pattern.compile("\\(([^)]*)\\)\\s*=>\\s*([^{][^,;\\)\\]]*?)([,;\\)\\]])");
        Matcher m4 = p4.matcher(code);
        StringBuffer sb4 = new StringBuffer();
        while (m4.find()) {
            String params = m4.group(1);
            String expr = m4.group(2).trim();
            String terminator = m4.group(3);
            m4.appendReplacement(sb4, Matcher.quoteReplacement("function(" + params + ") { return " + expr + "; }" + terminator));
        }
        m4.appendTail(sb4);
        code = sb4.toString();
        
        // Pattern 5: Single parameter without parentheses: x => expr
        // Convert to: function(x) { return expr; }
        Pattern p5 = Pattern.compile("\\b([a-zA-Z_$][a-zA-Z0-9_$]*)\\s*=>\\s*([^{][^,;\\)\\]]*?)([,;\\)\\]])");
        Matcher m5 = p5.matcher(code);
        StringBuffer sb5 = new StringBuffer();
        while (m5.find()) {
            String param = m5.group(1);
            String expr = m5.group(2).trim();
            String terminator = m5.group(3);
            m5.appendReplacement(sb5, Matcher.quoteReplacement("function(" + param + ") { return " + expr + "; }" + terminator));
        }
        m5.appendTail(sb5);
        code = sb5.toString();
        
        return code;
    }
}
